### ISSUE TITLE
Overlaps with dkstat?

### ISSUE THREAD

**Issue by sebastianbarfort** [ekstroem/dst#1]
Hi Claus, 

just wanted to make sure you're aware of [dkstat](https://github.com/rOpenGov/dkstat). The package is in very early beta but might be worth taking a look at. 

Best, 
Sebastian

**Comment by ekstroem** [comment]
Ah! I didn't know about Kenneth's project. I'll throw my efforts into improving that instead of reinventing the wheel.

Thanks!
